# Generated by Django 3.2.5 on 2023-04-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='transitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name_1', models.CharField(max_length=100)),
                ('image_name_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='image_coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
                ('new_image_name', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('N', 'N'), ('S', 'S'), ('E', 'E'), ('W', 'W')], max_length=1)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makemap.map')),
            ],
        ),
    ]
