# Generated by Django 3.2.5 on 2023-04-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makemap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_coordinates',
            name='direction',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('S', 'S'), ('E', 'E'), ('W', 'W')], max_length=1, null=True),
        ),
    ]
