# Generated by Django 3.2.5 on 2023-04-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makemap', '0002_alter_image_coordinates_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_coordinates',
            name='map',
            field=models.IntegerField(),
        ),
    ]
